USE [master]
GO

/****** Object:  Database [MaestroDetalle]    Script Date: 8/9/2021 11:30:52:a. m. ******/
CREATE DATABASE [MaestroDetalle]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MaestroDetalle', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.ELMERSERVER\MSSQL\DATA\MaestroDetalle.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MaestroDetalle_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.ELMERSERVER\MSSQL\DATA\MaestroDetalle_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MaestroDetalle].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MaestroDetalle] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MaestroDetalle] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MaestroDetalle] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MaestroDetalle] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MaestroDetalle] SET ARITHABORT OFF 
GO

ALTER DATABASE [MaestroDetalle] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MaestroDetalle] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MaestroDetalle] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MaestroDetalle] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MaestroDetalle] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MaestroDetalle] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MaestroDetalle] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MaestroDetalle] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MaestroDetalle] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MaestroDetalle] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MaestroDetalle] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MaestroDetalle] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MaestroDetalle] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MaestroDetalle] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MaestroDetalle] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MaestroDetalle] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MaestroDetalle] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MaestroDetalle] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MaestroDetalle] SET  MULTI_USER 
GO

ALTER DATABASE [MaestroDetalle] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MaestroDetalle] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MaestroDetalle] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MaestroDetalle] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MaestroDetalle] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MaestroDetalle] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MaestroDetalle] SET  READ_WRITE 
GO


